version: 3
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
           name: Initial build
           command: ./gradlew clean assembledebug --no-daemon --stacktrace
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - deploy:
          name: "Deploy to Fabric 🎉🎉"
          command: |
            echo "Branch: ${CIRCLE_BRANCH} , PR: ${CIRCLE_PULL_REQUEST}"
            if [ "${CIRCLE_BRANCH}" == "master" -o "${CIRCLE_PULL_REQUEST}" != "" ]; then
              ./gradlew assembledebug crashlyticsUploadDistributiondebug --stacktrace --debug --no-daemon
            fi
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
               echo "Currently on Dev Branch we should not deploy on fabric"
            fi

            release=$(cut -c-7 <<< "${CIRCLE_BRANCH}")
            if [ "$release" == "release"]; then
              ./gradlew crashlyticsUploadDistributionProductionRelease --stacktrace --debug --no-daemon
            fi


